name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
        env:
          CI: true
      - name: Build package
        run: npm run build
      - name: Test package
        run: npm run test
      - name: Lint package
        run: npm run lint
