name: Validate config of renovate

on:
  pull_request:
    paths:
      - "renovate.json"

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: "14.x"
      - name: Validate config
        run: npx --package renovate -c 'renovate-config-validator'
